### ISSUE TITLE
Avoid Consuming stream when creating object list

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/lib-s34k-core#2]
## Overview
Currently, entire stream of objects is consumed when initializing[ the BasicObjectList](https://github.com/VEuPathDB/lib-s34k-core/blob/main/src/main/kotlin/org/veupathdb/lib/s3/s34k/core/objects/BasicObjectList.kt#L38). We can avoid eagerly consuming the stream to support memory-sensitive use-cases.

**Comment by Foxcapades** [comment]
This may be a breaking change as we may need to drop the `get` operator overloads.  This would mean a change in the s34k API project upstream of this as the get methods are declared in the API
